from __future__ import annotations

from typing import Optional, Protocol

from domain.wishlist.entities import Wishlist, WishlistItem


class WishlistRepository(Protocol):
    def list_for_user(self, *, owner_id: str) -> list[Wishlist]: ...
    def get(self, *, wishlist_id: str) -> Optional[Wishlist]: ...
    def get_by_share_token(self, *, token: str) -> Optional[Wishlist]: ...
    def create(self, wishlist: Wishlist) -> Wishlist: ...
    def update(self, *, wishlist_id: str, fields: dict) -> Optional[Wishlist]: ...
    def delete(self, *, wishlist_id: str) -> None: ...
    def create_item(self, item: WishlistItem) -> WishlistItem: ...
    def update_item(self, *, item_id: str, wishlist_id: str, fields: dict) -> Optional[WishlistItem]: ...
    def delete_item(self, *, item_id: str, wishlist_id: str) -> None: ...
